//! Deterministic generator for the Phase 0 sheet benchmark corpus.
//!
//! Produces 16 raster icon sheets plus per-sheet ground-truth JSON and a
//! manifest, all committed to `bench/corpus`:
//!
//! * sheets 01–10: the original connected-shape set (grouping gate),
//! * sheet 11 (C1): 1024-icon 4096² batch grid — throughput,
//! * sheet 12 (C2): 100-icon 4096² grid — the keystone latency sheet
//!   ("2 s / 100 icons"; flagged `keystone` in the manifest),
//! * sheet 13 (C7): JPEG-compressed grid (quality 85) — artifact robustness,
//! * sheet 14 (C8): colour icons (RGB PNG) — luma grouping over colour inks,
//! * sheet 15 (C9): near-duplicate icons — Phase 6 dedup corpus seeding,
//! * sheet 16 (C10): noisy scan (per-pixel background noise + isolated
//!   specks ≤ 3 px wide) — speckle-filter validation.
//!
//! Determinism contract (two parts):
//!
//! 1. **Pixel-exact, cross-language.** All rasterization below is
//!    *integer-only* and the RNG stream is consumed in a fixed order, so the
//!    committed corpus (generated by the mirrored `scripts/gen-corpus.mjs`)
//!    and this tool produce bit-identical pixel sets and truth. CI enforces
//!    this: it regenerates into `target/regen-corpus` and diffs every truth
//!    JSON byte-for-byte.
//! 2. **Container bytes may differ.** PNG/JPEG encoders are not part of the
//!    contract — only decoded pixels and the JSON sidecars are.
//!
//! Connected-shape rule (Phase 0 decision): every shape forms a single
//! 8-connected component, so the spike (which has no fragment merging — that
//! is Phase 3) can meet the gate honestly.

use image::{ExtendedColorType, ImageEncoder};
use serde_json::{json, Value};
use std::fs;
use std::path::Path;

/// LCG with the numerical-recipes constants (deterministic, portable).
///
/// The multiply wraps (`wrapping_mul`) — the JS mirror relies on the same
/// modular arithmetic, and debug builds must not panic on overflow.
struct Rng(u64);

impl Rng {
    fn new(seed: u64) -> Self {
        Self(seed)
    }
    fn next_u64(&mut self) -> u64 {
        self.0 = self
            .0
            .wrapping_mul(6364136223846348886)
            .wrapping_add(1442695040888963407);
        self.0
    }
    /// Uniform integer in `[lo, hi]` (inclusive).
    fn range(&mut self, lo: u32, hi: u32) -> u32 {
        if hi <= lo {
            return lo;
        }
        lo + (self.next_u64() % u64::from(hi - lo + 1)) as u32
    }
    /// Uniform signed integer in `[lo, hi]` (inclusive).
    fn range_i(&mut self, lo: i32, hi: i32) -> i32 {
        if hi <= lo {
            return lo;
        }
        lo + (self.next_u64() % u64::from((hi - lo) as u32 + 1)) as i32
    }
    fn pick<T: Clone>(&mut self, v: &[T]) -> T {
        v[(self.next_u64() % v.len() as u64) as usize].clone()
    }
}

type Luma = u8;

#[derive(Clone, Copy, Debug)]
struct BBox {
    x: i32,
    y: i32,
    w: i32,
    h: i32,
}

impl BBox {
    fn intersects_padded(&self, o: &BBox, gap: i32) -> bool {
        self.x < o.x + o.w + gap
            && o.x < self.x + self.w + gap
            && self.y < o.y + o.h + gap
            && o.y < self.y + self.h + gap
    }
}

/// Paints `1` into `cell` for every covered pixel; returns the tight bbox of
/// filled pixels within the `s × s` cell buffer.
///
/// All geometry is integer arithmetic (per-mille scaling where needed) so the
/// JS mirror in `scripts/gen-corpus.mjs` is bit-exact. `c` is the cell
/// center, `ux`/`uy` the signed offsets from it, `dx`/`dy` their absolute
/// values, `d2` the squared distance in 1/100-pixel units.
#[allow(clippy::needless_range_loop)] // pixel-grid indexing is the domain
fn rasterize_shape(shape: &str, s: u32, t: u32, cell: &mut [u8]) -> Option<BBox> {
    let s = i64::from(s);
    let t = i64::from(t);
    let c = (s - 1) / 2;
    let mut minx = i64::MAX;
    let mut miny = i64::MAX;
    let mut maxx = i64::MIN;
    let mut maxy = i64::MIN;

    for y in 0..s {
        for x in 0..s {
            let ux = x - c;
            let uy = y - c;
            let dx = ux.abs();
            let dy = uy.abs();
            let d2 = (100 * dx) * (100 * dx) + (100 * dy) * (100 * dy);
            let fill = match shape {
                "square" => true,
                "circle" => {
                    let r = 48 * s;
                    d2 <= r * r
                }
                "ring" => {
                    let r = 48 * s;
                    let ir = (r - 100 * t).max(1);
                    d2 <= r * r && d2 >= ir * ir
                }
                "frame" => {
                    let r = 46 * s;
                    let ir = (r - 100 * t).max(1);
                    d2 <= r * r && d2 >= ir * ir
                }
                "cross" => dx <= t || dy <= t,
                "plus" => {
                    let m = 38 * s / 100;
                    (dx <= t && dy <= m) || (dy <= t && dx <= m)
                }
                "diamond" => 100 * (dx + dy) <= 48 * s,
                "triangle" => {
                    let h = 96 * s / 100;
                    let half = 48 * s / 100;
                    let span = ((uy + h / 2) * half) / h;
                    uy.abs() <= h / 2 && dx <= span.max(0)
                }
                // True corner ("⌐"): bottom strip + right strip. The original
                // abs-coordinate version accidentally painted all four edges.
                "lshape" => {
                    let a = s / 2;
                    uy >= a - t || ux >= a - t
                }
                // Three horizontal bars joined by a left vertical spine —
                // CONNECTED by design (Phase 0 corpus decision; the old shape
                // was three separate strokes and needed Phase 3 merging).
                "bars" => {
                    let a = 44 * s / 100;
                    let band = 30 * s / 100;
                    let half_t = t / 2;
                    (ux <= -(a - t) && dy <= a)
                        || (dx <= a && (dy <= half_t || (dy - band).abs() <= half_t))
                }
                _ => false,
            };
            if fill {
                cell[(y * s + x) as usize] = 1;
                minx = minx.min(x);
                miny = miny.min(y);
                maxx = maxx.max(x);
                maxy = maxy.max(y);
            }
        }
    }
    if maxx < minx {
        None
    } else {
        Some(BBox {
            x: minx as i32,
            y: miny as i32,
            w: (maxx - minx + 1) as i32,
            h: (maxy - miny + 1) as i32,
        })
    }
}

struct Sheet {
    w: i32,
    h: i32,
    px: Vec<Luma>,
    placed: Vec<BBox>,
}

impl Sheet {
    fn new(w: u32, h: u32, bg: Luma) -> Self {
        Self {
            w: w as i32,
            h: h as i32,
            px: vec![bg; (w * h) as usize],
            placed: vec![],
        }
    }

    /// Stamps `shape` (top-left of its `s×s` cell at `tx,ty`); returns the
    /// tight bbox actually drawn, in sheet coordinates.
    ///
    /// F1 fix: painted pixels are tracked with an explicit cell mask, so ink
    /// colour 0 (black) is a perfectly valid paint value.
    fn stamp(&mut self, shape: &str, tx: i32, ty: i32, s: u32, t: u32, color: Luma) -> Option<BBox> {
        let mut cell = vec![0u8; (s * s) as usize];
        let bb = rasterize_shape(shape, s, t, &mut cell)?;
        let sx = tx + bb.x;
        let sy = ty + bb.y;
        if sx < 0 || sy < 0 || sx + bb.w > self.w || sy + bb.h > self.h {
            return None;
        }
        let si = s as i32;
        for y in bb.y..(bb.y + bb.h) {
            for x in bb.x..(bb.x + bb.w) {
                if cell[(y * si + x) as usize] == 1 {
                    let i = ((sy + (y - bb.y)) * self.w + (sx + (x - bb.x))) as usize;
                    self.px[i] = color;
                }
            }
        }
        let out = BBox {
            x: sx,
            y: sy,
            w: bb.w,
            h: bb.h,
        };
        self.placed.push(out);
        Some(out)
    }
}

#[derive(Clone, Copy)]
struct IconTruth {
    id: u32,
    shape: &'static str,
    bbox: BBox,
}

const SHAPES: &[&str] = &[
    "square", "circle", "ring", "cross", "plus", "diamond", "triangle", "frame", "lshape", "bars",
];

/// Stroke thickness picker per shape (deterministic within the sheet rng).
fn stroke_for(rng: &mut Rng, shape: &str, s: u32) -> u32 {
    match shape {
        "ring" | "frame" => rng.range(s / 8, s / 6).max(2),
        "cross" | "plus" => rng.range(s / 10, s / 8).max(2),
        "lshape" => rng.range(s / 8, s / 6).max(2),
        _ => rng.range(s / 10, s / 7).max(2),
    }
}

/// Per-cell parameters for [`build_grid`] (keeps the function under the
/// clippy argument limit and the call sites readable).
struct GridCfg {
    n: i32,
    sizes: (u32, u32),
    drift: i32,
    colors: (u8, u8),
}

fn build_grid(rng: &mut Rng, sheet: &mut Sheet, truth: &mut Vec<IconTruth>, cfg: GridCfg) {
    let margin = sheet.w / (2 * cfg.n).max(1);
    let cell = (sheet.w - 2 * margin) / cfg.n;
    for row in 0..cfg.n {
        for col in 0..cfg.n {
            let s = rng.range(cfg.sizes.0, cfg.sizes.1) as i32;
            let dx = if cfg.drift > 0 {
                rng.range_i(-cfg.drift, cfg.drift)
            } else {
                0
            };
            let dy = if cfg.drift > 0 {
                rng.range_i(-cfg.drift, cfg.drift)
            } else {
                0
            };
            let tx = margin + col * cell + (cell - s) / 2 + dx;
            let ty = margin + row * cell + (cell - s) / 2 + dy;
            // Guarded clamp (no panic when s outgrows the margins).
            let lo = margin / 2;
            let tx = tx.clamp(lo, (sheet.w - s - margin / 2).max(lo));
            let ty = ty.clamp(lo, (sheet.h - s - margin / 2).max(lo));
            let shape = rng.pick(SHAPES);
            let t = stroke_for(rng, shape, s as u32);
            let color = rng.range(u32::from(cfg.colors.0), u32::from(cfg.colors.1)) as u8;
            match sheet.stamp(shape, tx, ty, s as u32, t, color) {
                Some(bbox) => truth.push(IconTruth {
                    id: truth.len() as u32,
                    shape,
                    bbox,
                }),
                // drift pushed it out of the sheet — retry centered
                None => {
                    let tx2 = margin + col * cell + (cell - s) / 2;
                    let ty2 = margin + row * cell + (cell - s) / 2;
                    if let Some(bbox) = sheet.stamp(shape, tx2, ty2, s as u32, t, color) {
                        truth.push(IconTruth {
                            id: truth.len() as u32,
                            shape,
                            bbox,
                        });
                    }
                }
            }
        }
    }
}

/// Scattered layout: a loose 6×5 cell grid with random per-icon jitter.
/// Random-only rejection sampling fragments at this density; the jittered
/// grid guarantees the minimum gap while still looking scattered.
fn build_scattered(
    rng: &mut Rng,
    sheet: &mut Sheet,
    truth: &mut Vec<IconTruth>,
    count: usize,
    sizes: (u32, u32),
    gap: i32,
) {
    let cols = 6i32;
    let rows = ((count as i32) + cols - 1) / cols;
    let margin_x = sheet.w / ((2 * cols).max(1));
    let margin_y = sheet.h / ((2 * rows).max(1));
    let cellw = (sheet.w - 2 * margin_x) / cols;
    let cellh = (sheet.h - 2 * margin_y) / rows;
    // max icon + 2*jitter must stay below the cell so the gap survives
    let max_s = (sizes.1 as i32).max(0);
    let jitter = ((cellw.min(cellh) - max_s - gap) / 4).max(2);
    for i in 0..count {
        let col = (i as i32) % cols;
        let row = (i as i32) / cols;
        let s = rng.range(sizes.0, sizes.1) as i32;
        let shape = rng.pick(SHAPES);
        let t = stroke_for(rng, shape, s as u32);
        let color = rng.range(0, 40) as u8;
        let tx = margin_x + col * cellw + (cellw - s) / 2 + rng.range_i(-jitter, jitter);
        let ty = margin_y + row * cellh + (cellh - s) / 2 + rng.range_i(-jitter, jitter);
        let cand = BBox {
            x: tx,
            y: ty,
            w: s,
            h: s,
        };
        assert!(
            !sheet.placed.iter().any(|p| p.intersects_padded(&cand, gap)),
            "scattered layout violated the {gap}px gap"
        );
        let bbox = sheet
            .stamp(shape, tx, ty, s as u32, t, color)
            .unwrap_or_else(|| panic!("scattered stamp failed for shape {shape}"));
        truth.push(IconTruth {
            id: truth.len() as u32,
            shape,
            bbox,
        });
    }
}

fn build_edge_corner(rng: &mut Rng, sheet: &mut Sheet, truth: &mut Vec<IconTruth>) {
    let w = sheet.w;
    let h = sheet.h;
    let s = 56;
    let m = 2; // 2 px from the edge — must not touch the outermost ring
    let spots: [(i32, i32); 12] = [
        (m, m),
        (w - s - m, m),
        (m, h - s - m),
        (w - s - m, h - s - m),
        (w / 2 - s / 2, m),
        (w / 2 - s / 2, h - s - m),
        (m, h / 2 - s / 2),
        (w - s - m, h / 2 - s / 2),
        (w / 3, h / 3),
        (2 * w / 3 - s, h / 3),
        (w / 3, 2 * h / 3 - s),
        (2 * w / 3 - s, 2 * h / 3 - s),
    ];
    for (i, (tx, ty)) in spots.iter().enumerate() {
        let shape = SHAPES[(i * 3 + rng.range(0, 2) as usize) % SHAPES.len()];
        let t = rng.range(4, 8);
        let color = rng.range(0, 30) as u8;
        let bbox = sheet
            .stamp(shape, *tx, *ty, s as u32, t as u32, color)
            .unwrap_or_else(|| panic!("edge_corner stamp failed at {tx},{ty}"));
        truth.push(IconTruth {
            id: truth.len() as u32,
            shape,
            bbox,
        });
    }
}

/// C9 seeding: a 4×4 grid drawn from a small shape set with ±2 px size jitter
/// — near-duplicate icons for the Phase 6 dedup cascade.
fn build_duplicates(rng: &mut Rng, sheet: &mut Sheet, truth: &mut Vec<IconTruth>) {
    let n = 4i32;
    let set = ["circle", "square", "diamond", "ring"];
    let margin = sheet.w / (2 * n);
    let cell = (sheet.w - 2 * margin) / n;
    for row in 0..n {
        for col in 0..n {
            let s = 48 + rng.range_i(-2, 2);
            let shape = set[((row * n + col) as usize) % set.len()];
            let t = stroke_for(rng, shape, s as u32);
            let color = if rng.next_u64() % 4 == 0 { 20 } else { 0 };
            let tx = margin + col * cell + (cell - s) / 2;
            let ty = margin + row * cell + (cell - s) / 2;
            if let Some(bbox) = sheet.stamp(shape, tx, ty, s as u32, t, color) {
                truth.push(IconTruth {
                    id: truth.len() as u32,
                    shape,
                    bbox,
                });
            }
        }
    }
}

/// C10: low-quality scan — per-pixel background noise (fixed rng consumption:
/// one call per pixel, stamped over by icons afterwards), plus isolated dark
/// specks ≤ 3 px wide (area ≤ 9 < min_area 16) that the speckle filter must
/// drop. Specks are mutually separated (Chebyshev > 16) by skipping the paint
/// (never the rng draw) when a candidate lands too close to an existing one.
fn build_noisy(rng: &mut Rng, sheet: &mut Sheet, truth: &mut Vec<IconTruth>) {
    for v in &mut sheet.px {
        *v = 255u8.saturating_sub(rng.range(0, 13) as u8);
    }
    let n = 5i32;
    let rows = 4i32;
    let margin = 24i32;
    let cellw = (sheet.w - 2 * margin) / n;
    let cellh = (sheet.h - 2 * margin) / rows;
    for row in 0..rows {
        for col in 0..n {
            let s = rng.range(42, 54) as i32;
            let shape = rng.pick(SHAPES);
            let t = stroke_for(rng, shape, s as u32);
            let color = rng.range(0, 30) as u8;
            let tx = margin + col * cellw + (cellw - s) / 2;
            let ty = margin + row * cellh + (cellh - s) / 2;
            if let Some(bbox) = sheet.stamp(shape, tx, ty, s as u32, t, color) {
                truth.push(IconTruth {
                    id: truth.len() as u32,
                    shape,
                    bbox,
                });
            }
        }
    }
    let mut specks: Vec<(i32, i32)> = Vec::new();
    for _ in 0..14 {
        let sx = rng.range(8, (sheet.w - 12) as u32) as i32;
        let sy = rng.range(8, (sheet.h - 12) as u32) as i32;
        let side = rng.range(1, 3) as i32;
        let ok = specks
            .iter()
            .all(|(px, py)| (*px - sx).abs() > 16 || (*py - sy).abs() > 16);
        if ok {
            specks.push((sx, sy));
            for y in 0..side {
                for x in 0..side {
                    sheet.px[((sy + y) * sheet.w + (sx + x)) as usize] = 0;
                }
            }
        }
    }
}

/// C8 palette: luma value → RGB triple. The sheet is built in luma space
/// (geometry and grouping are luma-domain in Phase 0); encoding expands the
/// palette indices to solid colours. All palette lumas stay well below the
/// foreground cutoff (bg 255 − threshold 32 = 223).
const COLOUR_PALETTE: [(u8, u8, u8, u8); 5] = [
    // (luma, r, g, b)
    (76, 255, 0, 0),   // red
    (150, 0, 255, 0),  // green
    (29, 0, 0, 255),   // blue
    (151, 255, 128, 0), // orange
    (67, 128, 0, 255), // purple
];

fn build_colour(rng: &mut Rng, sheet: &mut Sheet, truth: &mut Vec<IconTruth>) {
    let n = 4i32;
    let margin = sheet.w / (2 * n);
    let cell = (sheet.w - 2 * margin) / n;
    for row in 0..n {
        for col in 0..n {
            let s = rng.range(44, 56) as i32;
            let shape = rng.pick(SHAPES);
            let t = stroke_for(rng, shape, s as u32);
            let color = COLOUR_PALETTE[((row * n + col) as usize) % COLOUR_PALETTE.len()].0;
            let tx = margin + col * cell + (cell - s) / 2;
            let ty = margin + row * cell + (cell - s) / 2;
            if let Some(bbox) = sheet.stamp(shape, tx, ty, s as u32, t, color) {
                truth.push(IconTruth {
                    id: truth.len() as u32,
                    shape,
                    bbox,
                });
            }
        }
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
enum Output {
    GrayPng,
    Jpeg,
    RgbPng,
}

type Builder = Box<dyn Fn(&mut Rng, &mut Sheet, &mut Vec<IconTruth>)>;

struct SheetSpec {
    name: &'static str,
    w: u32,
    h: u32,
    bg: Luma,
    keystone: bool,
    output: Output,
    build: Builder,
}

#[allow(clippy::too_many_arguments)]
fn sheet(
    name: &'static str,
    w: u32,
    h: u32,
    bg: Luma,
    keystone: bool,
    output: Output,
    build: Builder,
) -> SheetSpec {
    SheetSpec {
        name,
        w,
        h,
        bg,
        keystone,
        output,
        build,
    }
}

struct SheetResult {
    name: String,
    width: u32,
    height: u32,
    expected: usize,
    file_name: String,
    bytes: Vec<u8>,
    truth: Value,
}

fn generate_sheet(spec: &SheetSpec) -> SheetResult {
    let seed = 0x15A7_u64 ^ (spec.name.len() as u64).wrapping_mul(0x9E37_79B9_7F4A_7C15);
    let mut rng = Rng::new(seed);
    let mut sheet = Sheet::new(spec.w, spec.h, spec.bg);
    let mut truth: Vec<IconTruth> = vec![];
    (spec.build)(&mut rng, &mut sheet, &mut truth);

    let (file_name, bytes) = match spec.output {
        Output::GrayPng => {
            let mut png: Vec<u8> = Vec::new();
            image::codecs::png::PngEncoder::new(&mut png)
                .write_image(&sheet.px, spec.w, spec.h, ExtendedColorType::L8)
                .expect("png encode");
            (format!("{}.png", spec.name), png)
        }
        Output::Jpeg => {
            let mut jpg: Vec<u8> = Vec::new();
            image::codecs::jpeg::JpegEncoder::new_with_quality(&mut jpg, 85)
                .write_image(&sheet.px, spec.w, spec.h, ExtendedColorType::L8)
                .expect("jpeg encode");
            (format!("{}.jpg", spec.name), jpg)
        }
        Output::RgbPng => {
            let mut rgb: Vec<u8> = Vec::with_capacity(sheet.px.len() * 3);
            for &l in &sheet.px {
                let (_, r, g, b) = COLOUR_PALETTE
                    .iter()
                    .find(|(luma, _, _, _)| *luma == l)
                    .copied()
                    .unwrap_or((l, l, l, l));
                rgb.push(r);
                rgb.push(g);
                rgb.push(b);
            }
            let mut png: Vec<u8> = Vec::new();
            image::codecs::png::PngEncoder::new(&mut png)
                .write_image(&rgb, spec.w, spec.h, ExtendedColorType::Rgb8)
                .expect("png encode");
            (format!("{}.png", spec.name), png)
        }
    };

    let icons: Vec<Value> = truth
        .iter()
        .map(|t| {
            json!({
                "id": t.id,
                "shape": t.shape,
                "bbox": [t.bbox.x, t.bbox.y, t.bbox.w, t.bbox.h],
            })
        })
        .collect();
    let truth_json = json!({
        "file": file_name,
        "width": spec.w,
        "height": spec.h,
        "expected_groups": truth.len(),
        "icons": icons,
    });
    SheetResult {
        name: spec.name.to_string(),
        width: spec.w,
        height: spec.h,
        expected: truth.len(),
        file_name,
        bytes,
        truth: truth_json,
    }
}

pub fn generate_all(out_dir: &Path) -> usize {
    fs::create_dir_all(out_dir).expect("create out dir");
    let specs: Vec<SheetSpec> = vec![
        sheet(
            "01_basic_grid",
            512,
            512,
            255,
            false,
            Output::GrayPng,
            Box::new(|rng, sh, tr| build_grid(rng, sh, tr, GridCfg { n: 4, sizes: (44, 52), drift: 0, colors: (0, 20) })),
        ),
        sheet(
            "02_mixed_grid",
            768,
            768,
            244,
            false,
            Output::GrayPng,
            Box::new(|rng, sh, tr| build_grid(rng, sh, tr, GridCfg { n: 6, sizes: (32, 62), drift: 0, colors: (0, 40) })),
        ),
        sheet(
            "03_rings_holes",
            640,
            640,
            255,
            false,
            Output::GrayPng,
            Box::new(|rng, sh, tr| {
                // rings and frames only — connected components with holes
                let margin = sh.w / 10;
                let cell = (sh.w - 2 * margin) / 5;
                for row in 0..5i32 {
                    for col in 0..5i32 {
                        let s = rng.range(56, 64) as i32;
                        let shape = if rng.next_u64() % 2 == 0 { "ring" } else { "frame" };
                        let t = rng.range(10, 14);
                        let tx = margin + col * cell + (cell - s) / 2;
                        let ty = margin + row * cell + (cell - s) / 2;
                        if let Some(bbox) = sh.stamp(shape, tx, ty, s as u32, t, 0) {
                            tr.push(IconTruth {
                                id: tr.len() as u32,
                                shape,
                                bbox,
                            });
                        }
                    }
                }
            }),
        ),
        sheet(
            "04_scattered",
            768,
            768,
            250,
            false,
            Output::GrayPng,
            Box::new(|rng, sh, tr| build_scattered(rng, sh, tr, 30, (36, 56), 26)),
        ),
        sheet(
            "05_dense_grid",
            896,
            896,
            255,
            false,
            Output::GrayPng,
            Box::new(|rng, sh, tr| build_grid(rng, sh, tr, GridCfg { n: 8, sizes: (56, 64), drift: 0, colors: (0, 24) })),
        ),
        sheet(
            "06_thick_strokes",
            640,
            640,
            235,
            false,
            Output::GrayPng,
            Box::new(|rng, sh, tr| {
                // thick outlines only: ring/frame/cross/plus with heavy stroke
                let margin = sh.w / 10;
                let cell = (sh.w - 2 * margin) / 4;
                let shapes = ["ring", "frame", "cross", "plus"];
                for row in 0..4i32 {
                    for col in 0..4i32 {
                        let s = rng.range(88, 96) as i32;
                        let shape = shapes[(row * 4 + col) as usize % 4];
                        let t = rng.range(12, 18);
                        let tx = margin + col * cell + (cell - s) / 2;
                        let ty = margin + row * cell + (cell - s) / 2;
                        if let Some(bbox) = sh.stamp(shape, tx, ty, s as u32, t, 0) {
                            tr.push(IconTruth {
                                id: tr.len() as u32,
                                shape,
                                bbox,
                            });
                        }
                    }
                }
            }),
        ),
        sheet(
            "07_size_range",
            512,
            512,
            238,
            false,
            Output::GrayPng,
            Box::new(|rng, sh, tr| {
                let sizes = [20, 28, 36, 44, 52, 64, 76, 92, 116];
                let margin = sh.w / 7;
                let cell = (sh.w - 2 * margin) / 3;
                for i in 0..9usize {
                    let row = (i / 3) as i32;
                    let col = (i % 3) as i32;
                    let s = sizes[i] as i32;
                    let shape = SHAPES[i % SHAPES.len()];
                    let t = stroke_for(rng, shape, s as u32);
                    let tx = margin + col * cell + (cell - s) / 2;
                    let ty = margin + row * cell + (cell - s) / 2;
                    if let Some(bbox) = sh.stamp(shape, tx, ty, s as u32, t, 0) {
                        tr.push(IconTruth {
                            id: truth_len(tr),
                            shape,
                            bbox,
                        });
                    }
                }
            }),
        ),
        sheet(
            "08_grid_drift",
            768,
            768,
            255,
            false,
            Output::GrayPng,
            Box::new(|rng, sh, tr| build_grid(rng, sh, tr, GridCfg { n: 5, sizes: (48, 60), drift: 10, colors: (0, 30) })),
        ),
        sheet(
            "09_near_touching",
            640,
            640,
            255,
            false,
            Output::GrayPng,
            Box::new(|rng, sh, tr| {
                // 5×4 with only 4–6 px gaps between icons
                let n: i32 = 5;
                let mrows: i32 = 4;
                let margin = 16;
                let cellw = (sh.w - 2 * margin) / n;
                let cellh = (sh.h - 2 * margin) / mrows;
                for row in 0..mrows {
                    for col in 0..n {
                        // icon nearly fills the cell: only a 4–6 px gap remains
                        let s = (cellw.min(cellh) - rng.range_i(4, 6)).max(32);
                        let shape = rng.pick(SHAPES);
                        let t = rng.range(4, 6).max(2);
                        let tx = margin + col * cellw + (cellw - s) / 2;
                        let ty = margin + row * cellh + (cellh - s) / 2;
                        if let Some(bbox) = sh.stamp(shape, tx, ty, s as u32, t, 0) {
                            tr.push(IconTruth {
                                id: truth_len(tr),
                                shape,
                                bbox,
                            });
                        }
                    }
                }
            }),
        ),
        sheet(
            "10_edge_corner",
            640,
            640,
            255,
            false,
            Output::GrayPng,
            Box::new(|rng, sh, tr| build_edge_corner(rng, sh, tr)),
        ),
        // ---- extended corpus (C1/C2/C7–C10) ----
        sheet(
            "11_c1_batch_grid",
            4096,
            4096,
            255,
            false,
            Output::GrayPng,
            Box::new(|rng, sh, tr| build_grid(rng, sh, tr, GridCfg { n: 32, sizes: (40, 56), drift: 0, colors: (0, 24) })),
        ),
        sheet(
            "12_c2_latency_grid",
            4096,
            4096,
            255,
            true,
            Output::GrayPng,
            Box::new(|rng, sh, tr| build_grid(rng, sh, tr, GridCfg { n: 10, sizes: (120, 150), drift: 0, colors: (0, 24) })),
        ),
        sheet(
            "13_c7_jpeg_grid",
            768,
            768,
            247,
            false,
            Output::Jpeg,
            Box::new(|rng, sh, tr| build_grid(rng, sh, tr, GridCfg { n: 5, sizes: (48, 60), drift: 0, colors: (0, 30) })),
        ),
        sheet(
            "14_c8_colour_icons",
            512,
            512,
            255,
            false,
            Output::RgbPng,
            Box::new(|rng, sh, tr| build_colour(rng, sh, tr)),
        ),
        sheet(
            "15_c9_duplicates",
            512,
            512,
            255,
            false,
            Output::GrayPng,
            Box::new(|rng, sh, tr| build_duplicates(rng, sh, tr)),
        ),
        sheet(
            "16_c10_noisy_scan",
            640,
            640,
            255,
            false,
            Output::GrayPng,
            Box::new(|rng, sh, tr| build_noisy(rng, sh, tr)),
        ),
    ];

    let mut manifest_sheets: Vec<Value> = vec![];
    let mut total = 0usize;
    for spec in &specs {
        let res = generate_sheet(spec);
        fs::write(out_dir.join(&res.file_name), &res.bytes).expect("write image");
        fs::write(
            out_dir.join(format!("{}.json", res.name)),
            serde_json::to_string(&res.truth).unwrap(),
        )
        .expect("write truth");
        let mut entry = json!({
            "file": res.file_name,
            "truth": format!("{}.json", res.name),
            "width": res.width,
            "height": res.height,
            "expected_groups": res.expected,
        });
        if spec.keystone {
            entry["keystone"] = json!(true);
        }
        manifest_sheets.push(entry);
        total += res.expected;
        println!(
            "generated {:<22} {}x{} icons={:>4} bytes={}",
            res.name,
            res.width,
            res.height,
            res.expected,
            res.bytes.len()
        );
    }
    let manifest = json!({
        "corpus": "icon-forge/bench",
        "version": "0.1.0",
        "generated_by": "isg-gen-corpus (deterministic, fixed seed, integer rasterization)",
        "sheets": manifest_sheets,
        "total_icons": total,
    });
    fs::write(
        out_dir.join("manifest.json"),
        serde_json::to_string_pretty(&manifest).unwrap(),
    )
    .expect("write manifest");
    println!("total icons: {total}");
    total
}

fn main() {
    let mut out = Path::new("bench/corpus");
    let args: Vec<String> = std::env::args().collect();
    let mut i = 1;
    while i < args.len() {
        if args[i] == "--out" && i + 1 < args.len() {
            out = Path::new(&args[i + 1]);
            i += 2;
        } else {
            i += 1;
        }
    }
    generate_all(out);
}
 } else {
            i += 1;
        }
    }
    generate_all(out);
}
